### ISSUE TITLE
Prepare application summary

### ISSUE THREAD

**Issue by OleksiiDatsiuk** [Software-Engineering-LNU/Software-Engineering-Project#7]
- [x] Determine the project's goal, and the issues it solves.
- [x] Determine the project's target audience.
- [x] Application requirements

[Document](https://docs.google.com/document/d/1-tOIpj-n73os-muJZm3NyqMaF2VgLqztCnqj3e349-0)

**Comment by BeliaViktoria** [comment]
Nicely done!
